"""initial_schema

Revision ID: 6da4186c2256
Revises: 
Create Date: 2026-09-25 10:01:24.387589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6da4186c2256'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_goals')
    op.drop_table('xp_transactions')
    op.drop_table('vocabularies')
    op.drop_table('gem_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gem_transactions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('learner_id', sa.CHAR(length=32), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabularies',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('language_id', sa.CHAR(length=32), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('translation', sa.VARCHAR(), nullable=False),
    sa.Column('pronunciation_ipa', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xp_transactions',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('learner_id', sa.CHAR(length=32), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_goals',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('learner_id', sa.CHAR(length=32), nullable=False),
    sa.Column('target_xp', sa.INTEGER(), nullable=True),
    sa.Column('lessons_completed', sa.INTEGER(), nullable=True),
    sa.Column('last_completed_date', sa.DATETIME(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
